apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecostars.fullname" . }}-transactional-db-config
  labels:
    {{- include "ecostars.labels" . | nindent 4 }}
    app.kubernetes.io/component: transactional-db
data:
  POSTGRES_USER: {{ .Values.transactionalDb.credentials.user }}
  POSTGRES_DB: {{ .Values.transactionalDb.credentials.database }}