apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecostars.fullname" . }}-transactional-db-secret
  labels:
    {{- include "ecostars.labels" . | nindent 4 }}
    app.kubernetes.io/component: transactional-db
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.transactionalDb.credentials.password }}