#!/bin/bash

CREATE_TABLE_STATEMENT="CREATE TABLE IF NOT EXISTS metrics (
    id SERIAL PRIMARY KEY,
    metric_id VARCHAR(100) NOT NULL,
    item_type VARCHAR(100) NOT NULL,
    last_value VARCHAR(100) NOT NULL,
    last_measured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);"

POSTGRES_USER=postgres
POSTGRES_DB=postgres
TRANSACTIONAL_CONTAINER=transactional-db
docker exec -i "$TRANSACTIONAL_CONTAINER" \
  psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "$CREATE_TABLE_STATEMENT"