apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecostars.fullname" . }}-metabase
  labels:
    {{- include "ecostars.labels" . | nindent 4 }}
    app.kubernetes.io/component: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ecostars.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metabase
  template:
    metadata:
      labels:
        {{- include "ecostars.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: metabase
    spec:
      containers:
        - name: metabase
          image: "{{ .Values.metabase.image.repository }}:{{ .Values.metabase.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.metabase.port }}
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecostars.fullname" . }}-metabase
  labels:
    {{- include "ecostars.labels" . | nindent 4 }}
    app.kubernetes.io/component: metabase
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.metabase.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "ecostars.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: metabase